apiVersion: v1
kind: ReplicationController
metadata:
  name: centos-nfs-worker
spec:
  replicas: 2
  selector:
    name: centos-nfs-worker
  template:
    metadata:
      labels:
        name: centos-nfs-worker
    spec:
      containers:
      - image: centos
        command: ["sleep"]
        args: ["1d"]
        imagePullPolicy: IfNotPresent
        name: centos
        volumeMounts:
          - name: nfs1
            mountPath: "/download"
          - name: nfs2
            mountPath: "/upload"
      volumes:
      - name: nfs1
        persistentVolumeClaim:
          claimName: nfs1
      - name: nfs2
        persistentVolumeClaim:
          claimName: nfs2
     
 #
