apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: docker.io/jmeagher/jm-centos-nfs:latest
        #image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
          - mountPath: /data1
            name: hdd10gb
      volumes:
        - name: mypvc
          awsElasticBlockStore:
            volumeID: vol-65a4c0ed
            fsType: ext4
        - name: hdd10gb
          awsElasticBlockStore:
            volumeID: vol-8322480b
            fsType: ext4

