kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.0.202.230
    path: "/exports"

