kind: PersistentVolume
apiVersion: v1
metadata:
  name: nfs2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.0.202.230
    path: "/data1"

    #
    #
