apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-10-29T10:26:23Z
  generation: 2
  labels:
    run: oasis-api-runner
  name: oasis-api-runner
  namespace: default
  resourceVersion: "3033"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/oasis-api-runner
  uid: 2414b950-9dc2-11e6-beda-023cd4af42d7
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oasis-api-runner
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oasis-api-runner
    spec:
      containers:
      - image: coreoasis/api_runner:R_1_6_0_6
        imagePullPolicy: IfNotPresent
        name: oasis-api-runner
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
