apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2016-10-29T10:30:19Z
  generation: 2
  labels:
    run: oasis-mysql
  name: oasis-mysql
  namespace: default
  resourceVersion: "3120"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/oasis-mysql
  uid: b06a4255-9dc2-11e6-beda-023cd4af42d7
spec:
  replicas: 1
  selector:
    matchLabels:
      run: oasis-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: oasis-mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: celery
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: celery
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        name: oasis-mysql
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
