apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: centos
  #- image: gcr.io/google-samples/nfs-server:1.1
    name: test-container
    ports:
      - name: nfs
        containerPort: 2049
      - name: mountd
        containerPort: 20048
      - name: rpcbind
        containerPort: 111
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /exports
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: vol-65a4c0ed
      fsType: ext4


    #
    #
